FROM mirror.gcr.io/apache/hadoop:3.4.1

USER root

# Настроим архивные зеркала для CentOS 7
RUN sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# Установим EPEL и Python3
RUN yum install -y epel-release && \
    yum install -y python3 && \
    yum clean all

USER hadoop
CMD ["yarn", "nodemanager"]
